
-- Adding filegroups
ALTER DATABASE [VIA_HA_CIMSDEOnsite] ADD FILEGROUP [CIMSDE_2021];
ALTER DATABASE [VIA_HA_CIMSDEOnsite] ADD FILEGROUP [CIMSDE_2022];
ALTER DATABASE [VIA_HA_CIMSDEOnsite] ADD FILEGROUP [CIMSDE_2023];

-- Adding files to the filegroups
ALTER DATABASE [VIA_HA_CIMSDEOnsite] ADD FILE ( NAME = 'CIMSDE_2021', FILENAME = 'W:\Temp\!!POC_Data_Table_Partition\HA_Test_Datafiles\CIMSDE_2021.ndf') TO FILEGROUP [CIMSDE_2021];
ALTER DATABASE [VIA_HA_CIMSDEOnsite] ADD FILE ( NAME = 'CIMSDE_2022', FILENAME = 'W:\Temp\!!POC_Data_Table_Partition\HA_Test_Datafiles\CIMSDE_2022.ndf') TO FILEGROUP [CIMSDE_2022];
ALTER DATABASE [VIA_HA_CIMSDEOnsite] ADD FILE ( NAME = 'CIMSDE_2023', FILENAME = 'W:\Temp\!!POC_Data_Table_Partition\HA_Test_Datafiles\CIMSDE_2023.ndf') TO FILEGROUP [CIMSDE_2023];
