
-- Migrate each month's partition to the new filegroup
ALTER PARTITION FUNCTION pf_DateMonthly() MERGE RANGE ('2024-01-01');
ALTER PARTITION SCHEME ps_DateMonthly NEXT USED [CIMSDE_2024];
ALTER PARTITION FUNCTION pf_DateMonthly() SPLIT RANGE ('2024-01-01');

ALTER PARTITION FUNCTION pf_DateMonthly() MERGE RANGE ('2024-02-01');
ALTER PARTITION SCHEME ps_DateMonthly NEXT USED [CIMSDE_2024];
ALTER PARTITION FUNCTION pf_DateMonthly() SPLIT RANGE ('2024-02-01');

ALTER PARTITION FUNCTION pf_DateMonthly() MERGE RANGE ('2024-03-01');
ALTER PARTITION SCHEME ps_DateMonthly NEXT USED [CIMSDE_2024];
ALTER PARTITION FUNCTION pf_DateMonthly() SPLIT RANGE ('2024-03-01');

ALTER PARTITION FUNCTION pf_DateMonthly() MERGE RANGE ('2024-04-01');
ALTER PARTITION SCHEME ps_DateMonthly NEXT USED [CIMSDE_2024];
ALTER PARTITION FUNCTION pf_DateMonthly() SPLIT RANGE ('2024-04-01');

ALTER PARTITION FUNCTION pf_DateMonthly() MERGE RANGE ('2024-05-01');
ALTER PARTITION SCHEME ps_DateMonthly NEXT USED [CIMSDE_2024];
ALTER PARTITION FUNCTION pf_DateMonthly() SPLIT RANGE ('2024-05-01');

ALTER PARTITION FUNCTION pf_DateMonthly() MERGE RANGE ('2024-06-01');
ALTER PARTITION SCHEME ps_DateMonthly NEXT USED [CIMSDE_2024];
ALTER PARTITION FUNCTION pf_DateMonthly() SPLIT RANGE ('2024-06-01');

ALTER PARTITION FUNCTION pf_DateMonthly() MERGE RANGE ('2024-07-01');
ALTER PARTITION SCHEME ps_DateMonthly NEXT USED [CIMSDE_2024];
ALTER PARTITION FUNCTION pf_DateMonthly() SPLIT RANGE ('2024-07-01');

ALTER PARTITION FUNCTION pf_DateMonthly() MERGE RANGE ('2024-08-01');
ALTER PARTITION SCHEME ps_DateMonthly NEXT USED [CIMSDE_2024];
ALTER PARTITION FUNCTION pf_DateMonthly() SPLIT RANGE ('2024-08-01');

ALTER PARTITION FUNCTION pf_DateMonthly() MERGE RANGE ('2024-09-01');
ALTER PARTITION SCHEME ps_DateMonthly NEXT USED [CIMSDE_2024];
ALTER PARTITION FUNCTION pf_DateMonthly() SPLIT RANGE ('2024-09-01');

ALTER PARTITION FUNCTION pf_DateMonthly() MERGE RANGE ('2024-10-01');
ALTER PARTITION SCHEME ps_DateMonthly NEXT USED [CIMSDE_2024];
ALTER PARTITION FUNCTION pf_DateMonthly() SPLIT RANGE ('2024-10-01');

ALTER PARTITION FUNCTION pf_DateMonthly() MERGE RANGE ('2024-11-01');
ALTER PARTITION SCHEME ps_DateMonthly NEXT USED [CIMSDE_2024];
ALTER PARTITION FUNCTION pf_DateMonthly() SPLIT RANGE ('2024-11-01');

ALTER PARTITION FUNCTION pf_DateMonthly() MERGE RANGE ('2024-12-01');
ALTER PARTITION SCHEME ps_DateMonthly NEXT USED [CIMSDE_2024];
ALTER PARTITION FUNCTION pf_DateMonthly() SPLIT RANGE ('2024-12-01');
